# Wilderness Odyssey managed server.properties template
#
# Edit this file at: config/wildernessodysseyapi/server.properties
# On server start, this file syncs into the root server.properties.
# Changes apply after the next restart.

allow-flight=true
broadcast-console-to-ops=true
difficulty=normal
enable-command-block=true
enable-query=false
enable-rcon=false
enforce-whitelist=false
force-gamemode=false
gamemode=survival
generate-structures=true
hardcore=false
hide-online-players=false
level-type=minecraft\:normal
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
motd=A Wilderness Odyssey Server
network-compression-threshold=256
online-mode=true
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
rate-limit=0
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
use-native-transport=true
view-distance=10
white-list=false
