package com.thunder.wildernessodysseyapi.quest.world;

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.saveddata.SavedData;
import org.jetbrains.annotations.NotNull;

import java.util.HashSet;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;

/** Overworld shared facts. Identity is reconciled from the durable quest store, never generated by autosave. */
public final class QuestWorldSavedData extends SavedData {
    private UUID worldId;
    private Set<ResourceLocation> facts = Set.of();
    private CompoundTag unsupported;

    public QuestWorldSavedData() { }

    public QuestWorldSavedData(CompoundTag tag, HolderLookup.Provider registries) {
        if (!tag.contains("schemaVersion", Tag.TAG_INT) || tag.getInt("schemaVersion") != 1) {
            unsupported = tag.copy();
            return;
        }
        if (tag.contains("worldId") && !tag.hasUUID("worldId")) {
            unsupported = tag.copy();
            return;
        }
        worldId = tag.hasUUID("worldId") ? tag.getUUID("worldId") : null;
        var loaded = new HashSet<ResourceLocation>();
        if (!(tag.get("facts") instanceof ListTag list) || list.size() > 100_000) {
            unsupported = tag.copy();
            return;
        }
        for (var value : list) {
            var id = value instanceof StringTag ? ResourceLocation.tryParse(value.getAsString()) : null;
            if (id == null) {
                unsupported = tag.copy();
                return;
            }
            loaded.add(id);
        }
        facts = Set.copyOf(loaded);
    }

    public static QuestWorldSavedData get(MinecraftServer server) {
        if (!server.isSameThread()) throw new IllegalStateException("Quest world data must run on the server thread.");
        return server.overworld().getDataStorage().computeIfAbsent(new SavedData.Factory<>(QuestWorldSavedData::new, QuestWorldSavedData::new),
                "wildernessodysseyapi_quest_world");
    }

    public Optional<QuestWorldState> state() {
        return worldId == null || unsupported != null ? Optional.empty() : Optional.of(new QuestWorldState(worldId, facts));
    }

    public void reconcileIdentity(UUID durableWorldId) {
        if (unsupported != null) throw new IllegalStateException("Unsupported quest world data is preserved.");
        if (worldId != null && !worldId.equals(durableWorldId)) throw new IllegalStateException("Quest world identity does not match the durable store.");
        if (worldId == null) {
            worldId = durableWorldId;
            setDirty();
        }
    }

    public void update(QuestWorldState state) {
        reconcileIdentity(state.worldId());
        if (!facts.equals(state.facts())) {
            facts = state.facts();
            setDirty();
        }
    }

    @Override
    public @NotNull CompoundTag save(@NotNull CompoundTag tag, HolderLookup.@NotNull Provider registries) {
        if (unsupported != null) return unsupported.copy();
        tag.putInt("schemaVersion", 1);
        if (worldId != null) tag.putUUID("worldId", worldId);
        var values = new ListTag();
        facts.stream().map(ResourceLocation::toString).sorted().forEach(value -> values.add(StringTag.valueOf(value)));
        tag.put("facts", values);
        return tag;
    }
}
