package com.thunder.wildernessodysseyapi.ecosystem.service;

import com.thunder.wildernessodysseyapi.ecosystem.api.EnvironmentalContext;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.WeakHashMap;

/**
 * Bounded per-level history of recent player and animal disturbances.
 *
 * <p>The history is diagnostic and behavioral context only. It is deliberately
 * transient because old activity should not survive a server restart.</p>
 */
public final class DisturbanceMemoryService {

    private static final int MAXIMUM_DISTURBANCES_PER_LEVEL = 128;
    private static final long MEMORY_TICKS = 400L;
    private final Map<ServerLevel, Deque<EnvironmentalContext.Disturbance>> levels = new WeakHashMap<>();

    /** Records one bounded disturbance generated by a player or living entity. */
    public void record(ServerLevel level, BlockPos position, UUID sourceId, double intensity, long gameTime) {
        Deque<EnvironmentalContext.Disturbance> history = levels.computeIfAbsent(level, ignored -> new ArrayDeque<>());
        prune(history, gameTime);
        history.addLast(new EnvironmentalContext.Disturbance(
                position.immutable(),
                sourceId,
                Math.max(0.0, Math.min(1.0, intensity)),
                gameTime
        ));
        while (history.size() > MAXIMUM_DISTURBANCES_PER_LEVEL) {
            history.removeFirst();
        }
    }

    /** Returns the strongest recent local disturbance, biased toward proximity. */
    public Optional<EnvironmentalContext.Disturbance> nearest(
            ServerLevel level,
            BlockPos position,
            int radius,
            long gameTime
    ) {
        Deque<EnvironmentalContext.Disturbance> history = levels.get(level);
        if (history == null) {
            return Optional.empty();
        }
        prune(history, gameTime);
        double radiusSquared = (double) radius * radius;
        EnvironmentalContext.Disturbance best = null;
        double bestScore = 0.0;
        for (EnvironmentalContext.Disturbance disturbance : history) {
            double distanceSquared = disturbance.position().distSqr(position);
            if (distanceSquared > radiusSquared) {
                continue;
            }
            double recency = 1.0 - (gameTime - disturbance.createdAt()) / (double) MEMORY_TICKS;
            double score = disturbance.intensity() * Math.max(0.0, recency)
                    / Math.max(1.0, Math.sqrt(distanceSquared));
            if (score > bestScore) {
                bestScore = score;
                best = disturbance;
            }
        }
        return Optional.ofNullable(best);
    }

    /** Releases transient history for an unloading level. */
    public void clear(ServerLevel level) {
        levels.remove(level);
    }

    private static void prune(Deque<EnvironmentalContext.Disturbance> history, long gameTime) {
        while (!history.isEmpty() && gameTime - history.getFirst().createdAt() > MEMORY_TICKS) {
            history.removeFirst();
        }
    }
}
