name: Test and Publish Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Mod Jar
        run: ./gradlew build

      - name: Start Minecraft Server
        run: |
          ./gradlew runServer &
          sleep 60  # Wait for the server to start up

      - name: Run Client and Connect to Server
        run: |
          ./gradlew runClient &
          sleep 20  # Adjust as needed to ensure client connects

      - name: Run Game Tests
        run: ./gradlew test

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to GitHub Packages
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://maven.pkg.github.com/${{ github.repository_owner }}'

      - name: Publish to GitHub Packages
        run: ./gradlew publish
