name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build and run client
  client:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (required for Minecraft mod development)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build the mod
      - name: Build the mod
        run: ./gradlew build

      # Step 5: Run unit tests
      - name: Run tests
        run: ./gradlew test

      # Step 6: Run the Minecraft client (headless mode)
      - name: Run Minecraft client
        run: |
          mkdir -p minecraft-client
          curl -o minecraft-client/client.jar https://launcher.mojang.com/v1/objects/{client_version}/client.jar
          mkdir -p minecraft-client/mods
          cp build/libs/*.jar minecraft-client/mods/
          cd minecraft-client
          java -Xmx1G -Xms1G -cp client.jar net.minecraft.client.main.Main nogui

  # Job 2: Run Minecraft server (depends on client job)
  server:
    runs-on: ubuntu-latest
    needs: client

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (required for Minecraft mod development)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the mod
      - name: Build the mod
        run: ./gradlew build

      # Step 4: Download Minecraft Server
      - name: Download Minecraft Server
        run: |
          mkdir -p minecraft-server
          curl -o minecraft-server/server.jar https://launcher.mojang.com/v1/objects/{server_version}/server.jar

      # Step 5: Add mod to server mods folder
      - name: Add mod to server mods folder
        run: |
          mkdir -p minecraft-server/mods
          cp build/libs/*.jar minecraft-server/mods/

      # Step 6: Run Minecraft server (headless)
      - name: Start Minecraft server
        run: |
          cd minecraft-server
          java -Xmx1G -Xms1G -jar server.jar nogui
