name: Maven Publish

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags, e.g., v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GITHUB_ACTOR }}
                </username>
                <password>${{ secrets.GITHUB_TOKEN }}
                </password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build and Deploy to GitHub Packages
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
