name: Run Client and Server

on:
  push:
  pull_request:

jobs:
  startup-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Run server
        run: timeout 5m ./gradlew runServer --no-daemon

      - name: Run client
        env:
          JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
        run: timeout 5m ./gradlew runClient --no-daemon
